#ifndef MGL_INPUT_KEYBOARD_H
#define MGL_INPUT_KEYBOARD_H

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

	enum
	{
		MGL_KEYBOARD_Q,
		MGL_KEYBOARD_W,
		MGL_KEYBOARD_E,
		MGL_KEYBOARD_R,
		MGL_KEYBOARD_T,
		MGL_KEYBOARD_Y,
		MGL_KEYBOARD_U,
		MGL_KEYBOARD_I,
		MGL_KEYBOARD_O,
		MGL_KEYBOARD_P,
		MGL_KEYBOARD_A,
		MGL_KEYBOARD_S,
		MGL_KEYBOARD_D,
		MGL_KEYBOARD_F,
		MGL_KEYBOARD_G,
		MGL_KEYBOARD_H,
		MGL_KEYBOARD_J,
		MGL_KEYBOARD_K,
		MGL_KEYBOARD_L,
		MGL_KEYBOARD_Z,
		MGL_KEYBOARD_X,
		MGL_KEYBOARD_C,
		MGL_KEYBOARD_V,
		MGL_KEYBOARD_B,
		MGL_KEYBOARD_N,
		MGL_KEYBOARD_M,

		MGL_KEYBOARD_NUM1,
		MGL_KEYBOARD_NUM2,
		MGL_KEYBOARD_NUM3,
		MGL_KEYBOARD_NUM4,
		MGL_KEYBOARD_NUM5,
		MGL_KEYBOARD_NUM6,
		MGL_KEYBOARD_NUM7,
		MGL_KEYBOARD_NUM8,
		MGL_KEYBOARD_NUM9,
		MGL_KEYBOARD_NUM0,

		MGL_KEYBOARD_F1,
		MGL_KEYBOARD_F2,
		MGL_KEYBOARD_F3,
		MGL_KEYBOARD_F4,
		MGL_KEYBOARD_F5,
		MGL_KEYBOARD_F6,
		MGL_KEYBOARD_F7,
		MGL_KEYBOARD_F8,
		MGL_KEYBOARD_F9,
		MGL_KEYBOARD_F10,
		MGL_KEYBOARD_F11,
		MGL_KEYBOARD_F12,

		MGL_KEYBOARD_ESCAPE,
		MGL_KEYBOARD_TAB,
		MGL_KEYBOARD_CAPS,
		MGL_KEYBOARD_LSHIFT,
		MGL_KEYBOARD_RSHIFT,
		MGL_KEYBOARD_LCONTROL,
		MGL_KEYBOARD_RCONTROL,
		MGL_KEYBOARD_ALT,
		MGL_KEYBOARD_ALTGR,
		MGL_KEYBOARD_SPACE,
		MGL_KEYBOARD_ENTER,
		MGL_KEYBOARD_BACKSPACE,
		MGL_KEYBOARD_INSERT,
		MGL_KEYBOARD_DELETE,
		MGL_KEYBOARD_HOME,
		MGL_KEYBOARD_END,
		MGL_KEYBOARD_PAGEUP,
		MGL_KEYBOARD_PAGEDOWN,

		MGL_KEYBOARD_LEFT,
		MGL_KEYBOARD_RIGHT,
		MGL_KEYBOARD_UP,
		MGL_KEYBOARD_DOWN,

		MGL_KEYBOARD_KEY_COUNT
	};

	enum
	{
		MGL_KEY_MOD_NONE	= 0x00,
		MGL_KEY_MOD_SHIFT	= 0x01,
		MGL_KEY_MOD_CONTROL	= 0x02,
		MGL_KEY_MOD_ALT		= 0x04,
		MGL_KEY_MOD_SYSTEM	= 0x08,
	};

#ifdef __cplusplus
}
#endif // __cplusplus
#endif // MGL_INPUT_KEYBOARD_H
